import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/layouts/navbar/navbar";
import Footer from "@/app/components/layouts/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NTU Marriage Bureau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* ======================================================== */}
        {Array.isArray(children)
          ? children.map((child, index) => <div key={index}>{child}</div>)
          : children}
        {/* ======================================================== */}
        <Footer key="footer" />
      </body>
    </html>
  );
}